name: Build release
run-name: Build DBs and release
on: [push]
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build db files
        run: |
          ./build-release.sh >> $GITHUB_ENV
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          body: This release contains ${{ env.AIRCRAFT }} aircraft and ground vehicles.
          artifacts: |
            ./cotdb.txt
            ./cotdb.json
            ./cotdb_indexed.json
            ./countries.json
      - name: remove-old-releases
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 5
          delete_workflows: true
          workflows_keep_day: 2
          gh_token: ${{ secrets.GITHUB_TOKEN }}
